spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:3333/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 600000
      pool-name: library-db-pool
      connection-timeout: 100000
  jpa:
      hibernate:
        ddl-auto: update